services:
  epita-mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: EpitaMongoDB
    tty: true
    stdin_open: true
    extra_hosts:
          - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - ./../data:/app/data
      - ./../data-local:/app/data-local
    env_file:
      - .env
    command: ["/bin/bash"]